[FEAT] 34 - Técnica de brainstorm
Requisitos-de-Software/2022.2-Lichess pull request #45
Opened 2022-11-29 00:17 UTC by daves22

2022-11-29 11:37 UTC, Luckx98 requested changes
Ta show @daves22 , só deixei alguns comentários. Quando for arrumar, me coloca como revisor

2022-11-29 11:37 UTC, Luckx98 commented on docs/elicitacao/brainstorming.md
> +| 1   | O adversário deve poder filtrar os adversários |
Acho que ficou meio ambiguo, não seria melhor mudar para "O usuário deve poder filtrar os adversários" ?

2022-11-29 11:37 UTC, Luckx98 commented on docs/elicitacao/brainstorming.md
> +| 6   | O usuário deve poder continuar jogando de onde parou(quando offline) |
Esse requisito é o mesmo para tanto funcional quanto não funcional?

2022-11-29 11:37 UTC, Luckx98 commented on docs/elicitacao/brainstorming.md
> +> - Material apresentado para a disciplina de Requisitos de Software no curso de Engenharia de Software da UnB, FGA.
```suggestion
[1] - Simone Diniz, Interação Humano-Computador. São Paulo, 1a Edição, Elsevier, 2010.
[2] - Material apresentado para a disciplina de Requisitos de Software no curso de Engenharia de Software da UnB, FGA.
```

2022-11-29 13:26 UTC, nszchagas requested changes

2022-11-29 13:26 UTC, nszchagas commented on docs/elicitacao/brainstorming.md
> +| Número | Requisitos Funcionais |
Padronize a tabela de requisitos da mesma maneira que foi feito para as outras técnicas de elicitação. Um identificador, descrição e classificação entre requisito funcional (RF) e não funcional (RNF).

2022-11-29 21:19 UTC, daves22 commented on docs/elicitacao/brainstorming.md
> +| 1   | O adversário deve poder filtrar os adversários |
escrevi errado mesmo, obrigado pela observação

2022-11-29 23:00 UTC, Luckx98 approved these changes

2022-11-30 11:58 UTC, nszchagas approved these changes

2022-11-30 11:58 UTC, merged