Feat / ferramentas
Requisitos-de-Software/2022.2-Lichess pull request #7
Opened 2022-11-16 22:25 UTC by Luckx98

2022-11-16 23:58 UTC, nszchagas commented on docs/ferramentas.md
> +|  <img class="card-img img-fluid rounded" width="180" height="118" src="../docs/img/github-icon.png">  |       Github       | Será utilizado como repositório dos documentos produzidos e para o versi
Quando rodei o mkdocs localmente as imagens ficaram quebradas.
![image](https://user-images.githubusercontent.com/68018675/202320749-d87e9bc3-47da-4d81-a4b5-c0aede4c9866.png)

2022-11-16 23:59 UTC, nszchagas commented on mkdocs.yml
> +    - Ferramentas: ferramentas.md
Vamos manter uma organização nas pastas igual à dos menus na página? Sugiro colocar o arquivo ferramentas.md e a a pasta de imagens dentro da pasta "planejamento".

2022-11-18 03:43 UTC, lucasgabriel-2 commented on docs/planejamento/ferramentas.md
> +|  ![Github](../img/github-icon.png)  |      Github      | Será utilizado como repositório dos documentos produzidos e para o versionamento dos mesmos.
Apenas um detalhe, mas acredito que fique melhor da seguinte forma: "Utilizado como repositório dos documentos produzidos e para o versionamento dos mesmos."

2022-11-18 03:44 UTC, lucasgabriel-2 commented on docs/planejamento/ferramentas.md
> +| :---------------------------------------------------------------------------------------------------: | :--------------: | --------------------------------------------------------------------------
Adicionar o youtube como ferramenta para hospedagem das gravações das reuniões e a ferramenta utilizada para elaboração do Rich Picture

2022-11-18 04:17 UTC, lucasgabriel-2 commented on docs/planejamento/ferramentas.md
> +| 1.0    | 29/06/2022 | Adição das ferramentas do projeto | Lucas Macedo Barboza | ---     |
A data está errada

2022-11-18 04:23 UTC, lucasgabriel-2 commented on docs/planejamento/ferramentas.md
> +|  ![Teams](../img/teams-icon.png)   | Microsoft teams  | Nas apresentações dos pontos de controle foi utilizado para compartilhar a tela com a github pages, gravar a apresentação o projeto e elabora
Apenas um erro de digitação, na parte "dos artefatos do projeto"

2022-11-18 10:36 UTC, lucasgabriel-2 commented on docs/planejamento/ferramentas.md
> +| :---------------------------------------------------------------------------------------------------: | :--------------: | --------------------------------------------------------------------------
Seria interessante adicionar o vscode assim como no documento de IHC ?

2022-11-18 10:40 UTC, lucasgabriel-2 commented on docs/planejamento/ferramentas.md
> +<p> As ferramentas serão softwares utilizados pelo time do projeto para facilitar o gerenciamento, comunicação e desenvolvimento da documentação necessária para o tema utilizado na disciplina. Projet
Apenas um detalhe, mas acredito que fique melhor da seguinte forma: "As ferramentas serão softwares utilizados pela equipe para facilitar o gerenciamento, comunicação e desenvolvimento da documentação necessária para a realização do projeto da disciplina. Projeto esse que o foco será a análise de requisitos do aplicativo Lichess."

2022-11-18 10:42 UTC, lucasgabriel-2 requested changes
Por favor, observar os comentários.

2022-11-18 10:42 UTC, lucasgabriel-2 requested changes
Por favor, observar os comentários.

2022-11-18 14:56 UTC, nszchagas approved these changes

2022-11-18 15:04 UTC, lucasgabriel-2 approved these changes

2022-11-18 15:06 UTC, merged